require "user.plugins"
require "user.mappings"
require "user.settings"
-- require "user.bufferlinecfg"
require "user.cmp-config"
require "user.lsp-config"
require "user.nvim_tree"
require "user.telescope-config"
require "user.todocfg"
require "user.toggle-term"
require "user.treesitter"
require "user.whichkeycfg"
require "user.neoscrollcfg"
require "user.lualine"
require 'user.notify'
require "user.project"
require "user.lightspeed"
-- require "user.crates"
require "user.browse"
require "user.autopair"
require "user.jabs"
-- require "user.navic"
-- require "user.outline"
-- require "user.incline"
require "user.comments"
