require("fmst.mappings")
require("fmst.settings")
require("fmst.packer")
require("fmst.telescopecfg")
require("fmst.treesittercfg")
require("fmst.toggletermcfg")
require("fmst.whichcfg")
require("fmst.browsecfg")
require("fmst.notifycfg")
require("fmst.commentcfg")
require("fmst.autopaircfg")
require("fmst.lualinecfg")
require("fmst.harpooncfg")
require("fmst.lspcfg")
-- require("fmst.navbudcfg")
-- require("fmst.petscfg")
require("fmst.nvimtreecfg")
print("hello from fmst")

-- themes
-- require("fmst.catppuccino")
-- require("fmst.kanagawacfg")
-- require("fmst.tokyonightcfg")
